/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 04-abr.-2019 3:48:18 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `aerolineas` CASCADE
;

DROP TABLE IF EXISTS `aviones` CASCADE
;

DROP TABLE IF EXISTS `ciudades` CASCADE
;

DROP TABLE IF EXISTS `operarios` CASCADE
;

DROP TABLE IF EXISTS `rutas` CASCADE
;

DROP TABLE IF EXISTS `vuelos` CASCADE
;

/* Create Tables */

CREATE TABLE `aerolineas`
(
	`id_aerolineas` INT NOT NULL,
	`nombre_aerolineas` VARCHAR(50) NOT NULL,
	`estado_aerolineas` VARCHAR(50) NOT NULL,
	`fecha_reg_aerolineas` DATETIME NOT NULL,
	CONSTRAINT `PK_aerolineas` PRIMARY KEY (`id_aerolineas` ASC)
)

;

CREATE TABLE `aviones`
(
	`id_aviones` INT NOT NULL,
	`placa_aviones` VARCHAR(50) NOT NULL,
	`modelo_aviones` VARCHAR(50) NOT NULL,
	`capacidad_aviones` INT NOT NULL,
	`id_aerolineas_aviones` INT NOT NULL,
	`estado_aviones` VARCHAR(50) NOT NULL,
	`fecha_reg_aviones` DATETIME NOT NULL,
	CONSTRAINT `PK_aviones` PRIMARY KEY (`id_aviones` ASC)
)

;

CREATE TABLE `ciudades`
(
	`id_ciudades` INT NOT NULL,
	`nombre_cuidades` VARCHAR(255) NOT NULL,
	`prefijo_cuidades` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_ciudades` PRIMARY KEY (`id_ciudades` ASC)
)

;

CREATE TABLE `operarios`
(
	`id_operarios` INT NOT NULL,
	`fecha_nac_operarios` DATE NOT NULL,
	`fecha_reg_operarios` DATETIME NOT NULL,
	`cedula_operarios` VARCHAR(50) NOT NULL,
	`nombre_operarios` VARCHAR(255) NOT NULL,
	`correo_operarios` VARCHAR(255) NOT NULL,
	`sexo_operarios` BOOL NOT NULL,
	CONSTRAINT `PK_operarios` PRIMARY KEY (`id_operarios` ASC)
)

;

CREATE TABLE `rutas`
(
	`id_rutas` INT NOT NULL,
	`ciudad_origen_rutas` INT NOT NULL,
	`ciudad_destino_rutas` INT NOT NULL,
	`estado_rutas` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_rutas` PRIMARY KEY (`id_rutas` ASC)
)

;

CREATE TABLE `vuelos`
(
	`id_vuelos` INT NOT NULL,
	`fecha_reg_vuelos` DATETIME NOT NULL,
	`avion_vuelos` INT NOT NULL,
	`operario_vuelos` INT NOT NULL,
	`rutas_vuelos` INT NOT NULL,
	`estado_vuelos` VARCHAR(50) NOT NULL,
	`hora_llegada_vuelos` DATETIME NOT NULL,
	`hora_salida_vuelos` DATETIME NOT NULL,
	CONSTRAINT `PK_vuelos` PRIMARY KEY (`id_vuelos` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `aviones` 
 ADD INDEX `IXFK_aviones_aerolineas` (`id_aerolineas_aviones` ASC)
;

ALTER TABLE `rutas` 
 ADD INDEX `IXFK_rutas_ciudades` (`ciudad_origen_rutas` ASC)
;

ALTER TABLE `rutas` 
 ADD INDEX `IXFK_rutas_ciudades_02` (`ciudad_destino_rutas` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_aviones` (`avion_vuelos` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_operarios` (`operario_vuelos` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_rutas` (`rutas_vuelos` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `aviones` 
 ADD CONSTRAINT `FK_aviones_aerolineas`
	FOREIGN KEY (`id_aerolineas_aviones`) REFERENCES `aerolineas` (`id_aerolineas`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `rutas` 
 ADD CONSTRAINT `FK_rutas_ciudades`
	FOREIGN KEY (`ciudad_origen_rutas`) REFERENCES `ciudades` (`id_ciudades`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `rutas` 
 ADD CONSTRAINT `FK_rutas_ciudades_02`
	FOREIGN KEY (`ciudad_destino_rutas`) REFERENCES `ciudades` (`id_ciudades`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_aviones`
	FOREIGN KEY (`avion_vuelos`) REFERENCES `aviones` (`id_aviones`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_operarios`
	FOREIGN KEY (`operario_vuelos`) REFERENCES `operarios` (`id_operarios`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_rutas`
	FOREIGN KEY (`rutas_vuelos`) REFERENCES `rutas` (`id_rutas`) ON DELETE Restrict ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;

INSERT INTO `ciudades` (`id_ciudades`, `nombre_cuidades`, `prefijo_cuidades`) 
VALUES (100004, 'Bogota', 'BG');
INSERT INTO `ciudades` (`id_ciudades`, `nombre_cuidades`, `prefijo_cuidades`) 
VALUES (100005, 'Medellin', 'MD');
INSERT INTO `ciudades` (`id_ciudades`, `nombre_cuidades`, `prefijo_cuidades`) 
VALUES (100006, 'Cali', 'CL');

INSERT INTO `aerolineas` (`id_aerolineas`, `nombre_aerolineas`, `estado_aerolineas`, `fecha_reg_aerolineas`) 
VALUES ('100001', 'aerolinea pepito', 'enable', current_timestamp;
INSERT INTO `aerolineas` (`id_aerolineas`, `nombre_aerolineas`, `estado_aerolineas`, `fecha_reg_aerolineas`) 
VALUES ('100002', 'aerolinea pablito', 'enable', current_timestamp);
INSERT INTO `aerolineas` (`id_aerolineas`, `nombre_aerolineas`, `estado_aerolineas`, `fecha_reg_aerolineas`) 
VALUES ('100003', 'aerolinea prueba', 'enable', current_timestamp);

INSERT INTO `aviones` (`id_aviones`, `placa_aviones`, `modelo_aviones`, `capacidad_aviones`, `id_aerolineas_aviones`, `estado_aviones`, `fecha_reg_aviones`) VALUES (200001, '12301', 'boing', 400, 100001, 'enable', current_timestamp);
INSERT INTO `aviones` (`id_aviones`, `placa_aviones`, `modelo_aviones`, `capacidad_aviones`, `id_aerolineas_aviones`, `estado_aviones`, `fecha_reg_aviones`) VALUES (200002, '12302', 'boing2', 300, 100001, 'enable', current_timestamp);
INSERT INTO `aviones` (`id_aviones`, `placa_aviones`, `modelo_aviones`, `capacidad_aviones`, `id_aerolineas_aviones`, `estado_aviones`, `fecha_reg_aviones`) VALUES (200003, '12303', 'boing3', 200, 100001, 'enable', current_timestamp);

INSERT INTO `operarios` (`id_operarios`, `fecha_nac_operarios`, `fecha_reg_operarios`, `cedula_operarios`, `nombre_operarios`, `correo_operarios`, `sexo_operarios`)
VALUES (400001, current_timestamp, current_timestamp, '10101012145', 'operario1', 'operario1@correo.com', true);
INSERT INTO `operarios` (`id_operarios`, `fecha_nac_operarios`, `fecha_reg_operarios`, `cedula_operarios`, `nombre_operarios`, `correo_operarios`, `sexo_operarios`) 
VALUES (400002, current_timestamp, current_timestamp, '10101012145', 'operario2', 'operario2@correo.com', false);
INSERT INTO `operarios` (`id_operarios`, `fecha_nac_operarios`, `fecha_reg_operarios`, `cedula_operarios`, `nombre_operarios`, `correo_operarios`, `sexo_operarios`) 
VALUES (400003, current_timestamp, current_timestamp, '10101012145', 'operario3', 'operario3@correo.com', true);

INSERT INTO `rutas` (`id_rutas`, `ciudad_origen_rutas`, `ciudad_destino_rutas`, `estado_rutas`) 
VALUES (50001, 700004, 700005, 'enable');
INSERT INTO `rutas` (`id_rutas`, `ciudad_origen_rutas`, `ciudad_destino_rutas`, `estado_rutas`) 
VALUES (50002, 700004, 700005, 'enable');
INSERT INTO `rutas` (`id_rutas`, `ciudad_origen_rutas`, `ciudad_destino_rutas`, `estado_rutas`) 
VALUES (50003, 700004, 700005, 'enable');


INSERT INTO `vuelos` (`id_vuelos`, `fecha_reg_vuelos`, `avion_vuelos`, `operario_vuelos`, `rutas_vuelos`, `estado_vuelos`, `hora_llegada_vuelos`, `hora_salida_vuelos`) 
VALUES (600001, current_timestamp, 200001, 400001, 50001, 'enable', current_timestamp, current_timestamp);
INSERT INTO `vuelos` (`id_vuelos`, `fecha_reg_vuelos`, `avion_vuelos`, `operario_vuelos`, `rutas_vuelos`, `estado_vuelos`, `hora_llegada_vuelos`, `hora_salida_vuelos`) 
VALUES (600002, current_timestamp, 200002, 400001, 50002, 'enable', current_timestamp, current_timestamp);
INSERT INTO `vuelos` (`id_vuelos`, `fecha_reg_vuelos`, `avion_vuelos`, `operario_vuelos`, `rutas_vuelos`, `estado_vuelos`, `hora_llegada_vuelos`, `hora_salida_vuelos`) 
VALUES (600003, current_timestamp, 200003, 400001, 50003, 'enable', current_timestamp, current_timestamp);