/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-abr.-2019 3:35:23 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `aerolineas` CASCADE
;

DROP TABLE IF EXISTS `aviones` CASCADE
;

DROP TABLE IF EXISTS `ciudades` CASCADE
;

DROP TABLE IF EXISTS `operarios` CASCADE
;

DROP TABLE IF EXISTS `rutas` CASCADE
;

DROP TABLE IF EXISTS `vuelos` CASCADE
;

/* Create Tables */

CREATE TABLE `aerolineas`
(
	`id_aerolineas` INT NOT NULL,
	`nombre_aerolineas` VARCHAR(50) NOT NULL,
	`estado_aerolineas` VARCHAR(50) NOT NULL,
	`fecha_reg_aerolineas` DATETIME NOT NULL,
	CONSTRAINT `PK_aerolineas` PRIMARY KEY (`id_aerolineas` ASC)
)

;

CREATE TABLE `aviones`
(
	`id_aviones` INT NOT NULL,
	`placa_aviones` VARCHAR(50) NOT NULL,
	`modelo_aviones` VARCHAR(50) NOT NULL,
	`capacidad_aviones` INT NOT NULL,
	`id_aerolineas_aviones` INT NOT NULL,
	`estado_aviones` VARCHAR(50) NOT NULL,
	`fecha_reg_aviones` DATETIME NOT NULL,
	CONSTRAINT `PK_aviones` PRIMARY KEY (`id_aviones` ASC)
)

;

CREATE TABLE `ciudades`
(
	`id_ciudades` INT NOT NULL,
	`nombre_cuidades` VARCHAR(255) NOT NULL,
	`prefijo_cuidades` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_ciudades` PRIMARY KEY (`id_ciudades` ASC)
)

;

CREATE TABLE `operarios`
(
	`id_operarios` INT NOT NULL,
	`fecha_nac_operarios` DATE NOT NULL,
	`fecha_reg_operarios` DATETIME NOT NULL,
	`cedula_operarios` VARCHAR(50) NOT NULL,
	`nombre_operarios` VARCHAR(255) NOT NULL,
	`correo_operarios` VARCHAR(255) NOT NULL,
	`sexo_operarios` BOOL NOT NULL,
	CONSTRAINT `PK_operarios` PRIMARY KEY (`id_operarios` ASC)
)

;

CREATE TABLE `rutas`
(
	`id_rutas` INT NOT NULL,
	`ciudad_origen_rutas` INT NOT NULL,
	`ciudad_destino_rutas` INT NOT NULL,
	`estado_rutas` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_rutas` PRIMARY KEY (`id_rutas` ASC)
)

;

CREATE TABLE `vuelos`
(
	`id_vuelos` INT NOT NULL,
	`fecha_reg_vuelos` DATETIME NOT NULL,
	`avion_vuelos` INT NOT NULL,
	`operario_vuelos` INT NOT NULL,
	`rutas_vuelos` INT NOT NULL,
	`estado_vuelos` VARCHAR(50) NOT NULL,
	`hora_llegada_vuelos` DATETIME NOT NULL,
	`hora_salida_vuelos` DATETIME NOT NULL,
	CONSTRAINT `PK_vuelos` PRIMARY KEY (`id_vuelos` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `aviones` 
 ADD INDEX `IXFK_aviones_aerolineas` (`id_aerolineas_aviones` ASC)
;

ALTER TABLE `rutas` 
 ADD INDEX `IXFK_rutas_ciudades` (`ciudad_origen_rutas` ASC)
;

ALTER TABLE `rutas` 
 ADD INDEX `IXFK_rutas_ciudades_02` (`ciudad_destino_rutas` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_aviones` (`avion_vuelos` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_operarios` (`operario_vuelos` ASC)
;

ALTER TABLE `vuelos` 
 ADD INDEX `IXFK_vuelos_rutas` (`rutas_vuelos` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `aviones` 
 ADD CONSTRAINT `FK_aviones_aerolineas`
	FOREIGN KEY (`id_aerolineas_aviones`) REFERENCES `aerolineas` (`id_aerolineas`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `rutas` 
 ADD CONSTRAINT `FK_rutas_ciudades`
	FOREIGN KEY (`ciudad_origen_rutas`) REFERENCES `ciudades` (`id_ciudades`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `rutas` 
 ADD CONSTRAINT `FK_rutas_ciudades_02`
	FOREIGN KEY (`ciudad_destino_rutas`) REFERENCES `ciudades` (`id_ciudades`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_aviones`
	FOREIGN KEY (`avion_vuelos`) REFERENCES `aviones` (`id_aviones`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_operarios`
	FOREIGN KEY (`operario_vuelos`) REFERENCES `operarios` (`id_operarios`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `vuelos` 
 ADD CONSTRAINT `FK_vuelos_rutas`
	FOREIGN KEY (`rutas_vuelos`) REFERENCES `rutas` (`id_rutas`) ON DELETE Restrict ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
