/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 11-ene.-2019 10:28:50 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `ct_tipos_documentos` CASCADE
;


/* Create Tables */


CREATE TABLE `ct_tipos_documentos`
(
	`id_tip_doc` INTEGER NOT NULL AUTO_INCREMENT,
	`tipo_documento` VARCHAR(25) NOT NULL,
	`iniciales_tip_doc` VARCHAR(3) NOT NULL,
	CONSTRAINT `PK_ct_tipos_documentos` PRIMARY KEY (`id_tip_doc` ASC)
)
COMMENT='Este catalogo es el de los tipos de documento de los usuarios'
;


SET FOREIGN_KEY_CHECKS=1 
;


/* Insertar registros*/
-- ----------------------------------------------------------------------

INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('Cedula' , 'CC');
INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('cedula extranjería' , 'CE');
INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('Pasaporte' , 'PA');
INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('Tarjeta Identidad' , 'TI');
INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('Nit' , 'NIT');
INSERT INTO ct_tipos_documentos ( tipo_documento, iniciales_tip_doc )VALUES('Rup' , 'RUP');


-- ----------------------------------------------------------------------
